controle_banca/urls.py
from django.contrib import admin
from django.urls import path
from usuarios.views import index
from bilhetes.views import registrar_bilhete, informacoes_bilhete

urlpatterns = [
    path('admin/', admin.site.urls),

    path(
        "",
        index,
        name="index",
    ),

    path(
        "registrar-bilhete/",
        registrar_bilhete,
        name="registrar_bilhete",
    ),
    path(
        "bilhetes/<int:id>",
        informacoes_bilhete,
        name="informacoes_bilhete",
    )
]

bancas/models.py
from django.db import models


class Banca(models.Model):


    usuario = models.OneToOneField(
        "usuarios.Usuario",
        verbose_name="Usuário",
        on_delete=models.PROTECT
    )
    
    nome_banca = models.CharField(
        verbose_name='Nome da Banca: ',
        max_length=100,
    )

    valor_inicial_banca = models.IntegerField(
        verbose_name='Valor inicial da banca',
    )

    data_inicio_banca = models.DateTimeField(
        verbose_name='Data inicio banca',
        auto_now_add=True,
    )

    

    class Meta:
        verbose_name="Banca"
        verbose_name_plural="Bancas"
        db_table="banca"
    
    def __str__(self):
        return self.nome_banca

bilhetes/models.py
from django.db import models


class Bilhete(models.Model):

    STATUS_BILHETE = [
        ("AGUARDANDO", "Aguardando"),
        ("GREEN", "Green"),
        ("RED", "Red")

    ]

    status = models.CharField(
        verbose_name='status',
        max_length=11,
        choices = STATUS_BILHETE,
        default="AGUARDANDO"
    )

    time_casa = models.CharField(
        verbose_name="Time jogando em casa",
        max_length=194,
        blank=True,
        null=True

    )

    time_fora = models.CharField(
        verbose_name="Time jogando fora",
        max_length=194,
        blank=True,
        null=True

    )

    valor_aposta = models.IntegerField(
        verbose_name='Valor apostado R$',
   )

    cotacao = models.FloatField(
        verbose_name="Cotação"
   )

    banca_apostada = models.ForeignKey(
        'bancas.Banca',
        verbose_name='Banca que aconteceu a aposta',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        
    )

    horario_aposta = models.DateTimeField(
        verbose_name='Horario aposta',
        auto_now_add=True
    )

    def get_jogo(self):
        time_home = str(self.time_casa)
        time_away = str(self.time_fora)

        jogo_formatado = f'{time_home} x {time_away}'

        return jogo_formatado
    
    

    def get_valor_aposta(self):
        valor = self.valor_aposta

        valor_formatado = f'R$ {valor}'

        return valor_formatado

    def valor_ganho(self):
        valor = self.valor_aposta
        cotacao = self.cotacao

        ganho = valor * cotacao
        ganho_total = "{:.2f}".format(ganho)
        ganho_formatado = f"R$ {ganho_total}"


        return ganho_formatado

         

    class Meta:
        verbose_name ='Bilhete'
        verbose_name_plural ='Bilhetes',
        db_table ='bilhete'

    def __str__(self):
        return self.time_casa

usuarios/models.py
import email
from locale import normalize
from statistics import mode
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager,
    AbstractBaseUser,
    PermissionsMixin,
)


class UsuarioManager(BaseUserManager):

    def create_user(self, email, password=None):
        usuario = self.model(
        email=self.normalize_email(email)
    )

        usuario.is_active = True
        usuario.is_staff = False
        usuario.is_superuser = False

        if password:
            usuario.set_password(password)

        usuario.save()
        return usuario

    def create_superuser(self, email, password):
        usuario = self.create_user(
            email=self.normalize_email(email),
            password=password
        )

        usuario.is_active = True
        usuario.is_staff = True
        usuario.is_superuser = True

        usuario.set_password(password)

        usuario.save()

        return usuario


class Usuario(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(
        verbose_name="E-mail do usuário",
        max_length=194,
        unique=True,
    )

    is_active = models.BooleanField(
        verbose_name="O usuário está ativo",
        default=True,
    )

    is_staff = models.BooleanField(
        verbose_name="Usuário é da equipe de desenvolvimento",
        default=False,
    )


    is_superuser = models.BooleanField(
        verbose_name="Super usuario",
        default=False,
    )

    USERNAME_FIELD = "email"

    objects = UsuarioManager()

    class Meta:
        verbose_name="Usuário"
        verbose_name_plural ="Usuários"
        db_table = "usuario"

    def __str__(self):
        return self.email

bilhetes/forms.py
from dataclasses import fields
from django import forms
from bilhetes.models import Bilhete 

class BilheteForm(forms.ModelForm):

    

    class Meta:
        model = Bilhete
        fields = [
            "time_casa", "time_fora", "valor_aposta", 
            "cotacao", "banca_apostada", "status"
        ]

class AtualizaBilheteForm(forms.ModelForm):
    
    status_bilhete = forms.ChoiceField(required=True)

    class Meta:
        model = Bilhete
        fields = [
            "status"
        ]
        error_messages = {
            "status": {
                "required": "Por favor, atualize o status do bilhete"
            }
        }

bancas/views.py
from django.shortcuts import render

bilhetes/views.py
from django.contrib import messages
from django.shortcuts import (
    render, redirect, get_object_or_404
)
from bilhetes.models import Bilhete
from bilhetes.forms import BilheteForm, AtualizaBilheteForm
from django.utils import timezone

def registrar_bilhete(request):

    form = BilheteForm()


    if request.method == "POST":
        form = BilheteForm(request.POST)

        if form.is_valid():
            bilhete = form.save(commit=False)


            bilhete.banca_apostada = request.user.banca
            bilhete.save()


            messages.success(
                request,
                "Bilhete registrado com sucesso"
            )

            return redirect("index")

    

    context = {
        "nome_pagina": "registrar_bilhete",
        "form": form
    }

    return render(request, "registrar_bilhete.html", context)

def informacoes_bilhete(request, id):

    bilhete = get_object_or_404(
        Bilhete,
        id=id
    )

    form = AtualizaBilheteForm()
    

    if request.method == "POST":
        form = AtualizaBilheteForm(
            request.POST,
            instance=bilhete
        )

        if form.is_valid():
            bilhete = form.save(commit=False)

            bilhete.status = "AGUARDANDO"
            
            bilhete.save()

            messages.success(
                request,
                "Bilhete atualizado com sucesso"
            )

            return redirect("index")
    
    context = {
        "nome_pagina": "Informações Bilhetes",
        "bilhete": bilhete,
        "form": form
    }
    
    return render(request, "informacoes_bilhete.html", context)

usuarios/views.py
from django.shortcuts import render
from bilhetes.models import Bilhete


def index(request):

    todos_bilhetes = Bilhete.objects.all()

    context = {
        "nome_pagina": "Inicio da dashboard",
        'todos_bilhetes': todos_bilhetes,

    }
    return render(request, "index.html", context)

templates/base.html
<!DOCTYPE html>

{% load static %}


<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>Controle banca | Django Framework na prática</title>
        
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        
        <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">    
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    </head>

    <body id="page-top">
        <div id="wrapper">
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                    <div class="sidebar-brand-icon rotate-n-15">
                        <i class="fas fa-user-shield"></i>
                    </div>
                    
                    <div class="sidebar-brand-text">Controle Banca</div>
                </a>
                
                <hr class="sidebar-divider my-0">
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">
                        <i class="fas fa-home"></i>
                        <span>Início</span>
                    </a>
                </li>
                
                <hr class="sidebar-divider">
            </ul>

            <div id="content-wrapper" class="d-flex flex-column">
                <div id="content">
                    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>
                        
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown no-arrow">
                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="mr-2 d-none d-lg-inline text-gray-800 small">
                                        <i class="fas fa-cog"></i>
                                    </span>
                                </a>
                                
                                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Sair
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </nav>

                    {% block conteudo %} {% endblock conteudo%}

                    <footer class="sticky-footer bg-white">
                        <div class="container my-auto">
                            <div class="copyright text-center my-auto">
                                <span>Copyright © Bwins </span>
                            </div>
                        </div>
                    </footer>
                </div>
            </div>

            <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="ModalLabel">Você realmente deseja sair?</h5>
                            
                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        
                        <div class="modal-body">Selecione "sair" se realmente deseja sair</div>
                        
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                            <a class="btn btn-primary" href="#">Sair</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block conteudo %}

<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>

        <a href="{% url 'registrar_bilhete' %}" class="btn btn-primary betn-icon-split btn-sm">
            <span class="text">Registrar Bilhete</span>
            
            <span class="icon text-white-50">
                <i class="fas fa-user-plus"></i>
            </span>
        </a>
    </div>
    {% if messages %}
        {% for mensagem in messages %}
            <div class="alert alert-success" role="alert">
                {{ mensagem }}
            </div>
        {% endfor %}

    {% endif %}

    <div class="row">
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Apostas Ganhas</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                        </div>
                        
                        <div class="col-auto">
                            <i class="fas fa-user-lock fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Lucro</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                        </div>
                        
                        <div class="col-auto">
                            <i class="fas fa-user-clock fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Visitas finalizadas</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user-check fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Visitantes registrados no mês atual</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">0</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-users fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-sm-flex align-items-center justify-content-between mb-4">
            <h6 class="m-0 font-weight-bold text-primary">Apostas recentes</h6>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <th>Partida</th>
                        
                        <th>valor aposta</th>
                        <th>cotacao</th>
                        <th>Prêmio</th>
                        <th>banca</th>
                        <th>horario aposta</th>
                        <th>Status Bilhete</th>
                        <th>Mais informações</th>
                    </thead>

                    <tbody>
                        {% for bilhete in todos_bilhetes %}
                            <tr>
                                <td>{{ bilhete.get_jogo }}</td>
                                <td>{{ bilhete.get_valor_aposta }}</td>
                                <td>{{ bilhete.cotacao }}</td>
                                <td>{{ bilhete.valor_ganho}}</td>                              
                                <td>{{ bilhete.banca_apostada}}</td>
                                <td>{{ bilhete.horario_aposta}}</td>
                                <td>{{ bilhete.status}}</td>
                                <td>
                                    <a href="{% url 'informacoes_bilhete' id=bilhete.id %}">
                                        Ver informações
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock conteudo %}

templates/informacoes_bilhete.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block conteudo %}
<div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>

        <div>
            <a href="#" class="btn btn-success btn-icon-split btn-sm" data-toggle="modal" data-target="#modal1">
                <span class="text">Atualizar bilhete</span>
                <span class="icon text-white-50">
                    <i class="fas fa-user-check"></i>
                </span>
            </a>
        </div>
    
    
    <div class="card shadow mb-4">        
        <div class="card-body">
            <h4 class="mb-3 text-primary">
                Informações gerais
            </h4>
        
            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Horário da aposta</label>
                        <input type="text" class="form-control" value="{{ bilhete.horario_aposta }}" disabled>
                    </div>

                    <div class="form-group col-md-6">
                        <label>Valor apostad</label>
                        <input type="text" class="form-control" value="{{ bilhete.get_valor_aposta }}" disabled>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label>Cotação</label>
                        <input type="text" class="form-control" value="{{ bilhete.cotacao }}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Prêmio</label>
                        <input type="text" class="form-control" value="{{ bilhete.valor_ganho }}" disabled>
                    </div>

                    
                </div>
            </form>
        
            <h4 class="mb-3 mt-4 text-primary">
                Informações pessoais
            </h4>
            
            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Time casa</label>
                        <input type="text" class="form-control" value="{{ bilhete.time_casa }}" disabled>
                    </div>

                    <div class="form-group col-md-6">
                        <label>Time Fora</label>
                        <input type="text" class="form-control" value="{{ bilhete.time_fora }}" disabled>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Data aposta</label>
                        <input type="text" class="form-control" value="{{ bilhete.horario_aposta }}" disabled>
                    </div>

                    
                </div>
            </form>
                    
            <p class="mr-2 mt-3 mb-4 text-right">
                <small>
                    Aposta registrada em {{ bilhete.horario_aposta }} na banca {{ bilhete.banca_apostada }}
                </small>
            </p>
        
            <div class="mr-1 text-right">
                <a href="{% url 'index' %}" class="btn btn-secondary text-white" type="button">
                    <span class="text">Voltar</span>
                </a>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Atualizar bilhete</h5>
                    
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                
                <div class="modal-body">
                    <form method="post">
                        {% csrf_token %}
    
                        <div class="form-group">
                            <label for="id_status" class="col-form-label">Status do bilhete</label>
                            {% render_field form.status placeholder="Atualize o bilhete" class="form-control" %}
                        </div>
                            
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-primary">atualizar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/registrar_bilhete.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block conteudo %}
<div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Registrar Bilhete</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <h4 class="mb-3 text-primary">
                Formulário para registro de novo bilhete
            </h4>
            <p class="mb-5 ml-1">
                <small>
                    O asterisco (*) indica que os campos são obrigatórios 
                </small>
            </p>

            {% if form.errors %}
                {% for field in form %}
                    {% if field.errors %}
                        {% for erro in field.errors %}
                            <div class="alert alert-warning" role="alert">
                                {{ erro }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
        
            {% endif %}
            <form method="post">
                <div class="form-row">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group col-md-12">
                            <label>{{ field.label }} {% if field.field.required%} * {% endif %}</label>
                            {% render_field field placeholder=field.label class="form-control" %}
                        </div>
                    {% endfor %}
                </div>
                <div class="text-right">
                    <button class="bn btn-primary" type="sumit">
                        <span class="text">Registrar Bilhete</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock conteudo %}